//USER
export const FETCH_REGISTER_REQUEST = 'FETCH_REGISTER_REQUEST';
export const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';
export const FETCH_REGISTER_FAILURE = 'FETCH_REGISTER_FAILURE';

export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';

export const SET_USER = 'SET_USER';
export const USER_LOGOUT = 'USER_LOGOUT';

//CLASSIFIEDS
export const FETCH_CLASSIFIEDS_REQUEST = 'FETCH_CLASSIFIEDS_REQUEST';
export const FETCH_CLASSIFIEDS_SUCCESS = 'FETCH_CLASSIFIEDS_SUCCESS';
export const FETCH_CLASSIFIEDS_FAILURE = 'FETCH_CLASSIFIEDS_FAILURE';

export const FETCH_FILTER_CLASSIFIEDS_REQUEST = 'FETCH_FILTER_CLASSIFIEDS_REQUEST';
export const FETCH_FILTER_CLASSIFIEDS_SUCCESS = 'FETCH_FILTER_CLASSIFIEDS_SUCCESS';
export const FETCH_FILTER_CLASSIFIEDS_FAILURE = 'FETCH_FILTER_CLASSIFIEDS_FAILURE';

export const FETCH_EDIT_CLASSIFIED_REQUEST = 'FETCH_EDIT_CLASSIFIED_REQUEST';
export const FETCH_EDIT_CLASSIFIED_SUCCESS = 'FETCH_EDIT_CLASSIFIED_SUCCESS';
export const FETCH_EDIT_CLASSIFIED_FAILURE = 'FETCH_EDIT_CLASSIFIED_FAILURE';

export const FETCH_NEW_CLASSIFIED_REQUEST = 'FETCH_NEW_CLASSIFIED_REQUEST';
export const FETCH_NEW_CLASSIFIED_SUCCESS = 'FETCH_NEW_CLASSIFIED_SUCCESS';
export const FETCH_NEW_CLASSIFIED_FAILURE = 'FETCH_NEW_CLASSIFIED_FAILURE';

export const FETCH_DETAIL_CLASSIFIED_REQUEST = 'FETCH_DETAIL_CLASSIFIED_REQUEST';
export const FETCH_DETAIL_CLASSIFIED_SUCCESS = 'FETCH_DETAIL_CLASSIFIED_SUCCESS';
export const FETCH_DETAIL_CLASSIFIED_FAILURE = 'FETCH_DETAIL_CLASSIFIED_FAILURE';

export const FETCH_TAGS_REQUEST = 'FETCH_TAGS_REQUEST';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE';